### PR TITLE
Add adda

### PR DESCRIPTION
**Pull request by Mayroung**

### CODE REVIEW

**Comment by Mayroung** [comment]
The ADDA method is a deep learning method proposed in 2017 for domain adaptation, aimed at solving the problem of different distributions of training data and test data. In deep learning tasks, the generalization ability of the trained model on new datasets often decreases due to the distribution differences between different datasets. The ADDA method minimizes the difference between source domain and target domain through adversarial training, thereby improving the model's generalization ability in the target domain.

**Comment by vigo999** [comment]
thanks for the contribution.
some comments:
1. could you please modify the copyright to xidian?
2. could you try on latest mindspore version 2.0?
3. i saw the ckpt file & onnx file. could you provide the download link like [ckpt](download_link)

**Comment by Mayroung** [comment]
> thanks for the contribution. some comments:
> 
> 1. could you please modify the copyright to xidian?
> 2. could you try on latest mindspore version 2.0?
> 3. i saw the ckpt file & onnx file. could you provide the download link like [ckpt](download_link)

   1.I have modified the copyright to Xidian. Please check if it is correct.
   2.Due to Huawei not providing us with computing resources related to Mindspore2.0, I can only provide code for Mindspore1.8.0 at present.
   3.Here is a download link for the ckpt file:   
      link：https://pan.baidu.com/s/1gBUC7Ij-92PBCVcUKbDb7w  
      extraction code：a5pm


> thanks for the contribution. some comments:
> 
> 1. could you please modify the copyright to xidian?
> 2. could you try on latest mindspore version 2.0?
> 3. i saw the ckpt file & onnx file. could you provide the download link like [ckpt](download_link)
1.l have modified the copyright to Xidian. Please check if it is correct.
2.Due to Huawei not providing us with computing resources related to Mindspore2.0, I can only provide code for Mindspore1.8.0 at present.
3.Here is a download link for the ckpt file:
link: https://pan.baidu.com/s/1YBoixnItD79IzXnKZwoRuw 
extraction code: 6hay

**Comment by Mayroung** [comment]
> thanks for the contribution. some comments:
> 
> 1. could you please modify the copyright to xidian?
> 2. could you try on latest mindspore version 2.0?
> 3. i saw the ckpt file & onnx file. could you provide the download link like [ckpt](download_link)
1.l have modified the copyright to Xidian. Please check if it is correct.
2.Due to Huawei not providing us with computing resources related to Mindspore2.0, I can only provide code for Mindspore1.8.0 at present.
3.Here is a download link for the ckpt file:
link: https://pan.baidu.com/s/1YBoixnItD79IzXnKZwoRuw 
extraction code: 6hay

**Comment by vigo999** [comment]
> > thanks for the contribution. some comments:
> > 
> > 1. could you please modify the copyright to xidian?
> > 2. could you try on latest mindspore version 2.0?
> > 3. i saw the ckpt file & onnx file. could you provide the download link like [ckpt](download_link)
> >    1.l have modified the copyright to Xidian. Please check if it is correct.
> >    2.Due to Huawei not providing us with computing resources related to Mindspore2.0, I can only provide code for Mindspore1.8.0 at present.
> >    3.Here is a download link for the ckpt file:
> >    link: https://pan.baidu.com/s/1YBoixnItD79IzXnKZwoRuw
> >    extraction code: 6hay

**Comment by vigo999** [comment]
ok, i will find ways to serve ckpt file.

**Pull request merged**
